devices: 1
max_steps: 2000000
val_check_interval: 10000
check_val_every_n_epoch: null
log_every_n_steps: 50
num_sanity_val_steps: -1
logger:
  class_path: lightning.pytorch.loggers.TensorBoardLogger
  init_args:
    save_dir: ./logs
    name: debug
    version: debug
callbacks:
- class_path: lightning.pytorch.callbacks.ModelCheckpoint
  init_args:
    save_last: True
    save_top_k: 5
    monitor: val/rd_loss
    mode: min
    filename: "{step:09d}-{val/rd_loss:.4f}-{val/psnr:.4f}-{val/bpd:.4f}"
    auto_insert_metric_name: False
- class_path: GlobalStepRichProgressBar


